# Generated by Django 3.2.8 on 2022-11-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonutInfo',
            fields=[
                ('donut_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'donut_info',
                'managed': False,
            },
        ),
    ]
